### ISSUE TITLE
/config/wizard/feature/OpenVPN_status/wizard-run not executable by default

### ISSUE THREAD

**Issue by r2munz** [rpodsada/edgeos-openvpn-status#1]
Hey,

thanks a lot for providing this useful wizard! 

In order to see clients under the VPN Clients tab, I had to 

`# chmod +x /config/wizard/feature/OpenVPN_status/wizard-run`

After changing permission to the script the clients were visible. Maybe you want to consider updating your documentation.

**Comment by rpodsada** [comment]
Ah, yes, thank you - I missed that. Updated!
